version: '3'

services:
  app:
    build: ./docker/python/
    restart: unless-stopped
    command: python run.py
    volumes: 
      - .:/code
      # - /dev/i2c-1:/dev/i2c-1
      - /var/run/docker.sock:/var/run/docker.sock
    devices:  
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
    ports: 
      - 5000:5000